;; This logfile was generated automatically by `xindy'
;; at 07.06.2015  09:03:03
;; Indexstyle: "92VtwtBpp8", Rawindex: "kTTgnnp69t", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "†»€" -> "C"
Letter-group: "„€¼" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "„€¼" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†»€" -> "C"